name: Build and Release Chrome Extension

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Create a ZIP file of the extension
      - name: Create ZIP file of the extension
        run: |
          mkdir -p release
          zip -r release/outlier-earnings-masker.zip manifest.json content.js
          ls -la release/

      # Step 3: Upload the artifact (ZIP file)
      - name: Upload the artifact (ZIP)
        uses: actions/upload-artifact@v3
        with:
          name: outlier-earnings-masker
          path: release/outlier-earnings-masker.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download the built artifact (ZIP file)
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: outlier-earnings-masker

      # Step 2: List files to verify artifact download
      - name: List downloaded files
        run: ls -la 

      # Step 3: Create a new release using PAT_TOKEN
      - name: Create a GitHub release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: "v${{ github.run_number }}"  # Auto-increments release version
          release_name: "v${{ github.run_number }}"  # Same as tag_name
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN2 }}  # Use the PAT instead of GITHUB_TOKEN

      # Step 4: Upload the ZIP file to the release
      - name: Upload the ZIP to the release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: outlier-earnings-masker.zip  # Use the downloaded artifact path
          asset_name: outlier-earnings-masker-v${{ github.run_number }}.zip
          asset_content_type: application/zip
